kind: Service
apiVersion: v1
metadata:
  name: krd-gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krd-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "krd-gateway"
    spec:
      containers:
        - name: gateway
          image: krd-gateway:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
